# Generated by Django 5.1.4 on 2024-12-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_add_initial_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problems.problemtag'),
        ),
    ]
