# Generated by Django 5.1.4 on 2024-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_test_problem_alter_test_stdin'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visible_tests_count',
            field=models.IntegerField(default=1),
        ),
    ]
