# Generated by Django 5.1.4 on 2024-12-29 13:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_visible_tests_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
    ]
