# Generated by Django 5.1.4 on 2025-01-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NP', 'PENDING'), ('OK', 'ACCEPTED'), ('RJ', 'REJECTED'), ('CE', 'COMPILATION_ERROR'), ('RE', 'RUNTIME_ERROR'), ('PE', 'PRESENTATION_ERROR'), ('WA', 'WRONG_ANSWER'), ('TL', 'TIME_LIMIT_EXCEEDED'), ('ML', 'MEMORY_LIMIT_EXCEEDED'), ('AW', 'AWAITING_MANUAL'), ('RM', 'REJECTED_MANUAL'), ('BA', 'BANNED')], default='NP', max_length=3)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='problems.submission')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.test')),
            ],
        ),
    ]
