# Generated by Django 5.1.4 on 2024-12-20 14:46

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrole_id_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='syscalluser',
            managers=[
                ('objects', users.managers.SyscallUserManager()),
            ],
        ),
    ]
