# Generated by Django 5.1.4 on 2025-01-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contestparticipant_is_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hide_problems_until_start',
            field=models.BooleanField(default=False),
        ),
    ]
